#!/bin/bash

DATE=$(date +%H-%M-%S)
DB_HOST=$1
DB_PASSWORD=$2
DB_NAME=$3
AWS_SECRET=$4
BUCKET_NAME=$5

mysqldump --column-statistics=0 -u root -h $DB_HOST -P 3307 --protocol=tcp -p$DB_PASSWORD $DB_NAME > /tmp/db-$DATE.sql && \
        export AWS_ACCESS_KEY=AKIAX2AM7Z2RPU6LPTIH && \
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET && \
        aws s3 cp /tmp/db-$DATE.sql s3://$BUCKET_NAME